### PR TITLE
Allow nested running

### PR DESCRIPTION
**Pull request by kelunik**

### CODE REVIEW

**Comment by WyriHaximus** [comment]
Wish it was that simple, thanks non the less as it is a good step in the right direction :+1:

**Comment by kelunik** [comment]
I know, the PR isn't complete. I quite a bit of uncommited code locally.

**Comment by WyriHaximus** [comment]
Ah doh my bad. How far did you get? Managed to get it working by swapping https://github.com/async-interop/event-loop-test/blob/master/src/Test.php#L64-L85 around so working on figuring out how that bit exactly works and what I need to do to get it working without swapping that code around

**Comment by kelunik** [comment]
I did move around quite a few things.

Removed https://github.com/WyriHaximus/reactphp-async-interop-loop/blob/master/src/ReactEventLoop.php#L407-L415 and https://github.com/WyriHaximus/reactphp-async-interop-loop/blob/master/src/ReactEventLoop.php#L421-L441, referencing doesn't disable or enable anything, it just keeps the loop running or not.

I added a nextTick checker, that checks for 0 referenced watchers and throws in that case to stop the loop.

What I tried to do now is activating watchers only after the tick / in nextTick, currently, all your watchers are enabled directly, but I have not finished that yet.

**Comment by WyriHaximus** [comment]
Thanks, I'll go over the spec again tonight as well to ensure I didn't miss anything. As it seems I miss interpreted the referencing. I've also just pushed a few small improvements from this morning, nothing fixing the nested feature though.

**Pull request merged**
