### PR TITLE
Correct defer ordering

### PR DESCRIPTION
**Pull request by kelunik**
This patch corrects the defer ordering. Additionally it fixes not running unreferenced defers.

### CODE REVIEW

**Comment by kelunik** [comment]
I still have one changed line in my working directory I'm not sure about.

```diff
diff --git a/src/ReactEventLoop.php b/src/ReactEventLoop.php
index 8eeb084..d70285a 100644
--- a/src/ReactEventLoop.php
+++ b/src/ReactEventLoop.php
@@ -145,7 +145,7 @@ final class ReactEventLoop extends Driver
                         continue;
                     }
 
-                    if ($this->watchers[$watcherId]->referenced === true) {
+                    if ($this->watchers[$watcherId]->enabled) {
                         $this->setDeferFutureTick();
                         break;
                     }
```

**Comment by kelunik** [comment]
3b8f582829450811a4bf3ba50def67e6951a7147 introduced that. I think the referenced check might be right, but it has to check all watchers, not just defers.

Does React have anything like `reference` / `unreference`?

**Comment by WyriHaximus** [comment]
Thanks! React doesn't have anything like `reference` / `unreference` which makes working on this package interesting. I think you're right, that `referenced` should be `enabled`, will ook into that + it I might have to change it on some more places.

**Comment by kelunik** [comment]
It will be needed on a lot of places. It might be easier to add something like that to React.

**Pull request merged**
