### PR TITLE
updated appveyor.yml and created a new file appveyor.bat

### PR DESCRIPTION
**Pull request by maayanktyagi**

### CODE REVIEW

**Comment by WyriHaximus** [comment]
Looks good thanks :+1:

**Comment by WyriHaximus** [comment]
P.S. I know tests are failing, but that is beyond the scope of this issue

**Comment by maayanktyagi** [comment]
Awesome!That was quite easy.

**Comment by WyriHaximus** [comment]
Exactly why I created them in the first place. Can do this myself, or create issues for Hacktoberfest and help others out :smile:

**Comment by maayanktyagi** [comment]
Great thought.People like you are the pillars of open source.

**Comment by maayanktyagi** [comment]
Could you please add Hacktoberfest label to this pull request?

**Comment by WyriHaximus** [comment]
Done

**Comment by maayanktyagi** [comment]
Thanks!!

**Pull request merged**
