### PR TITLE
Update composer.json provide to async-interop/event-loop-implementation ^0.4

### PR DESCRIPTION
**Pull request by davidwdan**

### CODE REVIEW

**Comment by WyriHaximus** [comment]
Awesome, thanks 👍

**Comment by WyriHaximus** [comment]
@davidwdan would you like a tag with that?

**Comment by davidwdan** [comment]
that would be great

**Comment by WyriHaximus** [comment]
Just tagged https://github.com/WyriHaximus/reactphp-async-interop-loop/releases/tag/0.2.0

**Pull request merged**
